name: Python

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 'Install Requirements'
        run: pip install -r src/requirements.txt

      - name: 'Run Script'
        env:
          appid: ${{ secrets.appid }}
          msdkEncodeParam: ${{ secrets.msdkEncodeParam }}
          openid: ${{ secrets.openid }}
          sig: ${{ secrets.sig }}
          timestamp: ${{ secrets.timestamp }}
          roleId: ${{ secrets.roleId }}
          userId: ${{ secrets.userId }}
          token: ${{ secrets.token }}
        run: python src/main.py >> src/run.log

      - name: 'Auto Commit'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_message: update run.log
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
